-- MySQL Script generated by MySQL Workbench
-- 05/08/16 23:24:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UnificaTipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UnificaTipos` (
  `idUnificaTipos` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idUnificaTipos`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UnificaTiposXContato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UnificaTiposXContato` (
  `Contato_idContato` INT NOT NULL COMMENT '',
  `UnificaTipos_idUnificaTipos` INT NOT NULL COMMENT '',
  INDEX `fk_UnificaContatoXContato_UnificaTipos1_idx` (`UnificaTipos_idUnificaTipos` ASC)  COMMENT '',
  CONSTRAINT `fk_UnificaContatoXContato_UnificaTipos1`
    FOREIGN KEY (`UnificaTipos_idUnificaTipos`)
    REFERENCES `mydb`.`UnificaTipos` (`idUnificaTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UnificaTiposXEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UnificaTiposXEndereco` (
  `UnificaTipos_idUnificaTipos` INT NOT NULL COMMENT '',
  `Endereco_idEndereco` INT NOT NULL COMMENT '',
  INDEX `fk_UnificaTiposXEndereco_UnificaTipos1_idx` (`UnificaTipos_idUnificaTipos` ASC)  COMMENT '',
  CONSTRAINT `fk_UnificaTiposXEndereco_UnificaTipos1`
    FOREIGN KEY (`UnificaTipos_idUnificaTipos`)
    REFERENCES `mydb`.`UnificaTipos` (`idUnificaTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TratamentoMedico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TratamentoMedico` (
  `idTratamentoMedico` INT NOT NULL COMMENT '',
  `Familia_idFamilia` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idTratamentoMedico`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NaoAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NaoAluno` (
  `idNaoAluno` INT NOT NULL COMMENT '',
  `Consulta_idConsulta` INT NOT NULL COMMENT '',
  `UnificaTipos_idUnificaTipos` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idNaoAluno`)  COMMENT '',
  INDEX `fk_NaoAluno_UnificaTipos1_idx` (`UnificaTipos_idUnificaTipos` ASC)  COMMENT '',
  CONSTRAINT `fk_NaoAluno_UnificaTipos1`
    FOREIGN KEY (`UnificaTipos_idUnificaTipos`)
    REFERENCES `mydb`.`UnificaTipos` (`idUnificaTipos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`condicao_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`condicao_saude` (
  `idcondicao_saude` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcondicao_saude`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_doenca` (
  `idtipo_doenca` INT NOT NULL COMMENT '',
  `condicao_saude_idcondicao_saude` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idtipo_doenca`)  COMMENT '',
  INDEX `fk_tipo_doenca_condicao_saude1_idx` (`condicao_saude_idcondicao_saude` ASC)  COMMENT '',
  CONSTRAINT `fk_tipo_doenca_condicao_saude1`
    FOREIGN KEY (`condicao_saude_idcondicao_saude`)
    REFERENCES `mydb`.`condicao_saude` (`idcondicao_saude`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`residencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`residencia` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  `valor_prestacao` DECIMAL(8,2) NULL COMMENT '',
  `proprietario` VARCHAR(45) NULL COMMENT '',
  `parentesco_proprietario` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo_familiar` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_residencia` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_grupo_familiar_residencia1_idx` (`id_residencia` ASC)  COMMENT '',
  CONSTRAINT `fk_grupo_familiar_residencia1`
    FOREIGN KEY (`id_residencia`)
    REFERENCES `mydb`.`residencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(50) NOT NULL COMMENT '',
  `id_estado` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_cidade_estado1_idx` (`id_estado` ASC)  COMMENT '',
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `mydb`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `lograduro` VARCHAR(60) NULL COMMENT '',
  `numero` VARCHAR(10) NULL COMMENT '',
  `bairro` VARCHAR(30) NULL COMMENT '',
  `CEP` VARCHAR(8) NULL COMMENT '',
  `ponto_de_referencia` VARCHAR(30) NULL COMMENT '',
  `id_cidade` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_endereco_cidade1_idx` (`id_cidade` ASC)  COMMENT '',
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `mydb`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(50) NOT NULL COMMENT '',
  `data_nascimento` DATE NOT NULL COMMENT '',
  `estado_civil` VARCHAR(15) NOT NULL COMMENT '',
  `sexo` CHAR(1) NOT NULL COMMENT '',
  `cpf` CHAR(11) NULL COMMENT '',
  `rg` VARCHAR(12) NULL COMMENT '',
  `renda` DECIMAL(8,2) NULL COMMENT '',
  `pessoacol` VARCHAR(45) NOT NULL COMMENT '',
  `endereco_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_pessoa_endereco1_idx` (`endereco_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pessoa_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`familiar` (
  `id` INT NOT NULL COMMENT '',
  `id_grupo_familiar` INT NOT NULL COMMENT '',
  `parentesco` VARCHAR(20) NULL COMMENT '',
  `idoso` TINYINT(1) NULL COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_familiar_familia1_idx` (`id_grupo_familiar` ASC)  COMMENT '',
  INDEX `fk_familiar_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_familiar_familia1`
    FOREIGN KEY (`id_grupo_familiar`)
    REFERENCES `mydb`.`grupo_familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_familiar_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`saude_do_familiar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`saude_do_familiar` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_familiar` INT NOT NULL COMMENT '',
  `usa_medicamento_continuo` TINYINT(1) NOT NULL COMMENT '',
  `despesa_mensal` DECIMAL(8,2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_saude_do_familiar_familiar1_idx` (`id_familiar` ASC)  COMMENT '',
  CONSTRAINT `fk_saude_do_familiar_familiar1`
    FOREIGN KEY (`id_familiar`)
    REFERENCES `mydb`.`familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_de_doenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_de_doenca` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(100) NOT NULL COMMENT '',
  `cid` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`condicao_de_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`condicao_de_saude` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(50) NOT NULL COMMENT '',
  `id_saude_do_familiar` INT NOT NULL COMMENT '',
  `id_tipo_de_doenca` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_condicao_de_saude_saude_do_familiar1_idx` (`id_saude_do_familiar` ASC)  COMMENT '',
  INDEX `fk_condicao_de_saude_tipo_de_doenca1_idx` (`id_tipo_de_doenca` ASC)  COMMENT '',
  CONSTRAINT `fk_condicao_de_saude_saude_do_familiar1`
    FOREIGN KEY (`id_saude_do_familiar`)
    REFERENCES `mydb`.`saude_do_familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_condicao_de_saude_tipo_de_doenca1`
    FOREIGN KEY (`id_tipo_de_doenca`)
    REFERENCES `mydb`.`tipo_de_doenca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imovel_alugado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imovel_alugado` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo` VARCHAR(30) NOT NULL COMMENT '',
  `quantidade` INT NOT NULL COMMENT '',
  `valor` DECIMAL(8,2) NOT NULL COMMENT '',
  `id_grupo_familiar` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_imovel_alugado_familia1_idx` (`id_grupo_familiar` ASC)  COMMENT '',
  CONSTRAINT `fk_imovel_alugado_familia1`
    FOREIGN KEY (`id_grupo_familiar`)
    REFERENCES `mydb`.`grupo_familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_grupo_familiar` INT NOT NULL COMMENT '',
  `tipo` VARCHAR(30) NOT NULL COMMENT '',
  `marca_modelo` VARCHAR(50) NOT NULL COMMENT '',
  `ano_fabricacao` INT NOT NULL COMMENT '',
  `utilizacao` VARCHAR(1) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_veiculo_familia1_idx` (`id_grupo_familiar` ASC)  COMMENT '',
  CONSTRAINT `fk_veiculo_familia1`
    FOREIGN KEY (`id_grupo_familiar`)
    REFERENCES `mydb`.`grupo_familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_despesa` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`despesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`despesa` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_grupo_familiar` INT NOT NULL COMMENT '',
  `id_tipo_despesa` INT NOT NULL COMMENT '',
  `valor` DECIMAL(8,2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_despesa_familia1_idx` (`id_grupo_familiar` ASC)  COMMENT '',
  INDEX `fk_despesa_tipo_despesa1_idx` (`id_tipo_despesa` ASC)  COMMENT '',
  CONSTRAINT `fk_despesa_familia1`
    FOREIGN KEY (`id_grupo_familiar`)
    REFERENCES `mydb`.`grupo_familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despesa_tipo_despesa1`
    FOREIGN KEY (`id_tipo_despesa`)
    REFERENCES `mydb`.`tipo_despesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`beneficio_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`beneficio_social` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_grupo_familiar` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `valor` DECIMAL(8,2) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_beneficio_social_familia1_idx` (`id_grupo_familiar` ASC)  COMMENT '',
  CONSTRAINT `fk_beneficio_social_familia1`
    FOREIGN KEY (`id_grupo_familiar`)
    REFERENCES `mydb`.`grupo_familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genitor` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  `local_de_trabaho` VARCHAR(60) NOT NULL COMMENT '',
  `cargo_funcao` VARCHAR(50) NOT NULL COMMENT '',
  `profissao` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_progenitor_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_progenitor_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsavel` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `url_documento_comprobatorio` VARCHAR(20) NOT NULL COMMENT '',
  `orgao_expedidor` VARCHAR(15) NOT NULL COMMENT '',
  `vigencia` VARCHAR(12) NOT NULL COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_responsavel_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_responsavel_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  `turno` CHAR(1) NOT NULL COMMENT '',
  `classificacao` CHAR(1) NOT NULL COMMENT '',
  `certidao_de_nascimento` VARCHAR(200) NOT NULL COMMENT '',
  `matricula_prefeitura` VARCHAR(30) NULL COMMENT '',
  `religiao` VARCHAR(20) NULL COMMENT '',
  `batizado` TINYINT(1) NULL COMMENT '',
  `url_foto` VARCHAR(255) NULL COMMENT '',
  `ano_do_aluno` VARCHAR(20) NULL COMMENT '',
  `grupo_familiar_id` INT NOT NULL COMMENT '',
  `genitor_id` INT NULL COMMENT '',
  `responsavel_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_aluno_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  INDEX `fk_aluno_grupo_familiar1_idx` (`grupo_familiar_id` ASC)  COMMENT '',
  INDEX `fk_aluno_genitor1_idx` (`genitor_id` ASC)  COMMENT '',
  INDEX `fk_aluno_responsavel1_idx` (`responsavel_id` ASC)  COMMENT '',
  CONSTRAINT `fk_aluno_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_grupo_familiar1`
    FOREIGN KEY (`grupo_familiar_id`)
    REFERENCES `mydb`.`grupo_familiar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_genitor1`
    FOREIGN KEY (`genitor_id`)
    REFERENCES `mydb`.`genitor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_responsavel1`
    FOREIGN KEY (`responsavel_id`)
    REFERENCES `mydb`.`responsavel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `id` INT NOT NULL COMMENT '',
  `telefone` VARCHAR(11) NOT NULL COMMENT '',
  `tipo` VARCHAR(15) NOT NULL COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_contato_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_contato_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requerimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requerimento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  `motivo_solicitacao` TEXT NULL COMMENT '',
  `data_solicitacao` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_requerimento_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_requerimento_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questionario_socio_economico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questionario_socio_economico` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  `ano_letivo` VARCHAR(10) NULL COMMENT '',
  `motivo_da_solicitacao` VARCHAR(40) NOT NULL COMMENT '',
  `registro_educacenso` VARCHAR(20) NULL COMMENT '',
  `data_questionario` DATE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_questionario_socio_economico_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_questionario_socio_economico_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  `data_consulta` VARCHAR(45) NULL COMMENT '',
  `peso` DOUBLE NULL COMMENT '',
  `altura` VARCHAR(45) NULL COMMENT '',
  `evolucao_medica` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_consulta_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  CONSTRAINT `fk_consulta_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pre_matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pre_matricula` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pessoa` INT NOT NULL COMMENT '',
  `data_prematricula` DATE NULL COMMENT '',
  `observacao` TEXT NULL COMMENT '',
  `ano_letivo` VARCHAR(10) NULL COMMENT '',
  `qnt_filhos_mae` INT NULL COMMENT '',
  `qnt_filhos_creche` INT NULL COMMENT '',
  INDEX `fk_pre_matricula_pessoa1_idx` (`id_pessoa` ASC)  COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_pre_matricula_pessoa1`
    FOREIGN KEY (`id_pessoa`)
    REFERENCES `mydb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
